# ######################
# SITE SETTINGS
# ######################

title: 喵落阁 # The name of your blog, used in titles and meta tags.
subTitle: 克喵的博客 # A short description that appears after the main title.
description: 克喵的博客，用于分享生活、资源和踩坑教学。 # A longer description for SEO and meta tags.
keywords: 'Suzu, Next.js, markdown blog, 克喵, blog, sakura, 克喵爱吃卤面' # Comma-separated keywords for SEO purposes.
author:
  name: 克喵爱吃卤面 # Your name, displayed as the author of the blog.
  link: 'https://www.kemiao.online' # Link to your personal website or blog.
# Language setting: Use ISO 639-1 code (e.g., 'en' for English, 'zh' for Chinese)
lang: zh-CN
# Your public root url, used for SEO and meta tags.
# !Do not include a ending slash
siteUrl: 'https://me.kemeow.top'

# Path to your avatar image. Can be a relative path from /public or a full URL (e.g., https://).
avatar: https://img.314926.xyz/images/2025/08/13/no-background-kemiaofxjun.webp
# Used as the default thumbnail for posts without thumbnails.
background: /images/background.jpg
# Slogan displayed on your homepage, under your avatar.
slogan: 愿你看清一切真相后，依旧热爱你的家人和朋友。
# Google Analytics tracking ID (e.g., 'G-XXXXXXXXXX'). Leave empty if you do not want to use Google Analytics.
googleAnalytics:

# ######################

# HTML HEAD SETTINGS
# ######################
# Feel free to add more links in Head for your site for better SEO.
# You could generate the links/icons by using https://realfavicongenerator.net/
# Recommend put your icons in /public/icons folder. And follow the examples below.
# Each item here will be rendered as a link tag in the <head> section of your site.
# <link rel="icon" type="image/png" href="/icons/favicon-96x96.png" sizes="96x96" />
# - rel
#   type(optional)
#   href
#   sizes(optional)
links:
  - rel: icon
    type: image/png
    href: /icons/favicon-96x96.png
    sizes: 96x96
  - rel: icon
    type: image/svg+xml
    href: /icons/favicon.svg
  - rel: apple-touch-icon
    href: /icons/apple-touch-icon.png
    sizes: 180x180

# ######################
# POSTS SETTINGS
# ######################
# How many posts you want to display per page. (default(not set): 5, max: 15)
postsPerPage: 10

# Your custom CC license for the posts.
creativeCommons:
  type: CC BY-SA 4.0 Deed
  link: https://creativecommons.org/licenses/by-sa/4.0/deed.zh-hans

# ######################
# HEADER SETTINGS
# ######################
# If you want to join the travellings community, set the following field to true.
# For more information, visit https://www.travellings.cn/en_US/
travellings: true

# ######################
# FOOTER SETTINGS
# ######################
# If you want to have a start year of your blog, set the year here.
startYear: 2025 # Leave empty if you do not want to display a start year.

# ######################
# PAGES SETTINGS
# ######################
# Add your AniList username if you want to display your AniList profile.
# Leave the field empty if you do not want to display your AniList profile.

anilist_username: kemiao # Your AniList username. https://anilist.co/user/username
# Set the desired anime name style you want to use.
# Options: 'romaji', 'english', 'native'
# Fallback to 'romaji' if the specified style is not available.
# Default for `ja` locale is 'native', for other locales is 'english'.
anilist_anime_name_style: english

# ######################
# SOCIAL MEDIA SETTINGS
# ######################
# Add your social media usernames.
# Leave the field empty if you do not want to display a specific platform.
# The order of the social media icons is determined by the order below.
socialMedia:
  github_username: Kemeow815 # Your GitHub username. https://github.com/username
  telegram_username: KemiaoJun # Your Telegram username. https://t.me/username
  bilibili_id: 3546643173477234 # Your Bilibili ID. https://space.bilibili.com/username
  email: me@mail.kemeow.top # Your email address.
  rss: true # Display the RSS icon. Set to false to hide the icon. Set empty to fully disable the RSS feed.
  qq: l355c7etFY
  music_id: 1725716511 # Your Music ID. https://music.163.com/user/username
  twitter_username: kemiaosw # Your Twitter username. https://twitter.com/username

# ######################
# COMMENTS SETTINGS
# Only one of the following two options should be enabled.
# Priority: Twikoo > Disqus
# ######################
# Your Twikoo environment ID.
twikooEnvId: https://twikoo-suzublog.kemeow.top
# Your Disqus shortname (used for integrating Disqus comments).
# Find this in your Disqus account: yoursite.disqus.com (shortname is the part before .disqus.com).
disqusShortname:

# ######################
# CUSTOM CODE BLOCKS
# ! WARNING: Only modify these if you understand the purpose of custom scripts.
# ######################
# Add custom JavaScript code to be included inside the <head> section of your site.
# One script url per line. Could be a CDN or a local file.
headerJavascript:
  - https://static.314926.xyz/js/suzublog/zlasica.js
# Add custom HTML code to be included inside the <footer> section of your site.
slotFooter: |
  <img src="https://img.shields.io/badge/欢迎来到克喵的博客-希望你在这里得偿所愿-4CAF50" alt="欢迎来到克喵的博客">
